import "./addNamePrefix.js";
import "./changeVoices.js";
import "./extensionIntro.js";
import "./linesFix.js";
import "./verifyVersion.js";
import "./playBGM.js";
import "./importCharacters.js";
import "./definePingZe.js";
import "./update.js";
